export const esVistaPrevia = import.meta.env.VITE_PREVIEW === "true";

export const usuarioPreview = {
  nombre_usuario: "preview",
  nombre_completo: "Vista previa",
  rol: "Consulta",
};

export const productosPreview = {
  ok: true,
  data: [
    {
      id_producto: 1,
      codigo: "ARZ-001",
      nombre: "Arroz extra",
      categoria: "Abarrotes",
      subcategoria: "Granos",
      marca: "Hipermaxi",
      estado: "ACTIVO",
      stock_minimo: 20,
      stock_maximo: 80,
      punto_reposicion: 25,
    },
    {
      id_producto: 2,
      codigo: "LEC-010",
      nombre: "Leche entera",
      categoria: "Lácteos",
      subcategoria: "Leche",
      marca: "Pil",
      estado: "ACTIVO",
      stock_minimo: 15,
      stock_maximo: 30,
      punto_reposicion: 20,
    },
    {
      id_producto: 3,
      codigo: "ACE-003",
      nombre: "Aceite vegetal",
      categoria: "Abarrotes",
      subcategoria: "Aceites",
      marca: "Fino",
      estado: "ACTIVO",
      stock_minimo: 8,
      stock_maximo: 40,
      punto_reposicion: 12,
    },
  ],
  pagination: { page: 1, limit: 10, total: 3 },
};

export const almacenesPreview = {
  ok: true,
  data: [
    {
      id_almacen: 1,
      codigo: "SUC-01",
      nombre: "Sucursal Centro",
      tipo: "SUCURSAL",
      ciudad: "Santa Cruz",
      capacidad: 500,
      ocupacion: 52,
      activo: true,
    },
  ],
  pagination: { page: 1, limit: 10, total: 1 },
};

export const stockAlmacenPreview = {
  ok: true,
  data: [
    {
      id_stock: 1,
      producto: "Arroz extra",
      producto_codigo: "ARZ-001",
      cantidad: 12,
      cantidad_reservada: 2,
      cantidad_disponible: 10,
      unidad: "kg",
      stock_minimo: 20,
      stock_maximo: 80,
      punto_reposicion: 25,
    },
    {
      id_stock: 2,
      producto: "Leche entera",
      producto_codigo: "LEC-010",
      cantidad: 40,
      cantidad_reservada: 0,
      cantidad_disponible: 40,
      unidad: "un",
      stock_minimo: 15,
      stock_maximo: 30,
      punto_reposicion: 20,
    },
    {
      id_stock: 3,
      producto: "Aceite vegetal",
      producto_codigo: "ACE-003",
      cantidad: 12,
      cantidad_reservada: 0,
      cantidad_disponible: 12,
      unidad: "lt",
      stock_minimo: 8,
      stock_maximo: 40,
      punto_reposicion: 12,
    },
  ],
};

export const consultaStockPreview = {
  ok: true,
  data: [
    {
      origen: "ALMACEN",
      id_registro: 1,
      producto: "Arroz extra",
      producto_codigo: "ARZ-001",
      almacen: "Sucursal Centro",
      almacen_codigo: "SUC-01",
      cantidad: 12,
      cantidad_reservada: 2,
      cantidad_disponible: 10,
      unidad: "kg",
      stock_minimo: 20,
      stock_maximo: 80,
      punto_reposicion: 25,
    },
    {
      origen: "ALMACEN",
      id_registro: 2,
      producto: "Leche entera",
      producto_codigo: "LEC-010",
      almacen: "Sucursal Centro",
      almacen_codigo: "SUC-01",
      cantidad: 40,
      cantidad_reservada: 0,
      cantidad_disponible: 40,
      unidad: "un",
      stock_minimo: 15,
      stock_maximo: 30,
      punto_reposicion: 20,
    },
    {
      origen: "ALMACEN",
      id_registro: 3,
      producto: "Aceite vegetal",
      producto_codigo: "ACE-003",
      almacen: "Sucursal Centro",
      almacen_codigo: "SUC-01",
      cantidad: 12,
      cantidad_reservada: 0,
      cantidad_disponible: 12,
      unidad: "lt",
      stock_minimo: 8,
      stock_maximo: 40,
      punto_reposicion: 12,
    },
  ],
  pagination: { page: 1, limit: 20, total: 3 },
};
